---
- hosts: routers
gather_facts: False
tasks:
- name: getting runing config
raw: show run
register: show_run
ignore-errors: yes

- local_action: copy content={{ show_run.stdout }} dest=/etc/ansible/backups/{{ inventory_hostname }}.txt
